### ISSUE TITLE
Post crash of broken news

### ISSUE THREAD

**Issue by mgracer48** [Spiderlover/Toontown-2.0#12]

**Comment by Spiderlover** [comment]
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 132, in __doPythonCallbacks
    self.MyEventmanager.doEvents()
  File "C:\Panda3D-1.9.0\direct\showbase\EventManager.py", line 55, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "C:\Panda3D-1.9.0\direct\showbase\EventManager.py", line 124, in processEvent
    messenger.send(eventName)
  File "C:\Panda3D-1.9.0\direct\showbase\Messenger.py", line 397, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.9.0\direct\showbase\Messenger.py", line 482, in __dispatch
    method (*(extraArgs + sentArgs))
  File "toontown\hood\Place.py", line 740, in teleportInDone
    self.fsm.request(self.nextState, [1])
  File "C:\Panda3D-1.9.0\direct\fsm\ClassicFSM.py", line 284, in request
    exitArgList)
  File "C:\Panda3D-1.9.0\direct\fsm\ClassicFSM.py", line 231, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Panda3D-1.9.0\direct\fsm\ClassicFSM.py", line 217, in __enter
    aState.enter(argList)
  File "C:\Panda3D-1.9.0\direct\fsm\State.py", line 203, in enter
    apply(self.__enterFunc, argList)
  File "toontown\safezone\Playground.py", line 499, in enterWalk
    Place.Place.enterWalk(self, teleportIn)
  File "toontown\hood\Place.py", line 209, in enterWalk
    self.walkStateData.enter()
  File "toontown\safezone\PublicWalk.py", line 22, in enter
    base.localAvatar.book.showButton()
  File "toontown\shtiker\ShtikerBook.py", line 335, in showButton
    localAvatar.newsButtonMgr.showAppropriateButton()
  File "toontown\toontowngui\NewsPageButtonManager.py", line 179, in showAppropriateButton
    self.request('NormalWalk')
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 322, in request
    self.__setState(*result)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 457, in __setState
    self.__callEnterFunc(self.newState, *args)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 493, in __callEnterFunc
    func(*args)
  File "toontown\toontowngui\NewsPageButtonManager.py", line 129, in enterNormalWalk
    if localAvatar.getLastTimeReadNews() < base.cr.inGameNewsMgr.getLatestIssue():
AttributeError: 'NoneType' object has no attribute 'getLatestIssue'
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 239, in run
    taskMgr.run()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
    self.step()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "C:\Panda3D-1.9.0\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 132, in __doPythonCallbacks
    self.MyEventmanager.doEvents()
  File "C:\Panda3D-1.9.0\direct\showbase\EventManager.py", line 55, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "C:\Panda3D-1.9.0\direct\showbase\EventManager.py", line 124, in processEvent
    messenger.send(eventName)
  File "C:\Panda3D-1.9.0\direct\showbase\Messenger.py", line 397, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.9.0\direct\showbase\Messenger.py", line 482, in __dispatch
    method (*(extraArgs + sentArgs))
  File "toontown\hood\Place.py", line 740, in teleportInDone
    self.fsm.request(self.nextState, [1])
  File "C:\Panda3D-1.9.0\direct\fsm\ClassicFSM.py", line 284, in request
    exitArgList)
  File "C:\Panda3D-1.9.0\direct\fsm\ClassicFSM.py", line 231, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Panda3D-1.9.0\direct\fsm\ClassicFSM.py", line 217, in __enter
    aState.enter(argList)
  File "C:\Panda3D-1.9.0\direct\fsm\State.py", line 203, in enter
    apply(self.__enterFunc, argList)
  File "toontown\safezone\Playground.py", line 499, in enterWalk
    Place.Place.enterWalk(self, teleportIn)
  File "toontown\hood\Place.py", line 209, in enterWalk
    self.walkStateData.enter()
  File "toontown\safezone\PublicWalk.py", line 22, in enter
    base.localAvatar.book.showButton()
  File "toontown\shtiker\ShtikerBook.py", line 335, in showButton
    localAvatar.newsButtonMgr.showAppropriateButton()
  File "toontown\toontowngui\NewsPageButtonManager.py", line 179, in showAppropriateButton
    self.request('NormalWalk')
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 322, in request
    self.__setState(*result)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 457, in __setState
    self.__callEnterFunc(self.newState, *args)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 493, in __callEnterFunc
    func(*args)
  File "toontown\toontowngui\NewsPageButtonManager.py", line 129, in enterNormalWalk
    if localAvatar.getLastTimeReadNews() < base.cr.inGameNewsMgr.getLatestIssue():
AttributeError: 'NoneType' object has no attribute 'getLatestIssue'
